//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C969_Project {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("C969_Project.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an appointment in the next 15 minutes!.
        /// </summary>
        internal static string AppointmentAlert {
            get {
                return ResourceManager.GetString("AppointmentAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update.
        /// </summary>
        internal static string ConfirmUpdate {
            get {
                return ResourceManager.GetString("ConfirmUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error populating database.
        /// </summary>
        internal static string ErrorPopulating {
            get {
                return ResourceManager.GetString("ErrorPopulating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing appointment selected. Please use Update or clear the fields before adding an appointment..
        /// </summary>
        internal static string ExistingAppointmentSelected {
            get {
                return ResourceManager.GetString("ExistingAppointmentSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing customer selected. Please use Update or Clear the fields before adding a new customer..
        /// </summary>
        internal static string ExistingCustomerSelected {
            get {
                return ResourceManager.GetString("ExistingCustomerSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding record failed. Please try again..
        /// </summary>
        internal static string FailedToAdd {
            get {
                return ResourceManager.GetString("FailedToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out all fields..
        /// </summary>
        internal static string FillOutAllFields {
            get {
                return ResourceManager.GetString("FillOutAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid appointment time..
        /// </summary>
        internal static string InvalidAppointmentTime {
            get {
                return ResourceManager.GetString("InvalidAppointmentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use a valid phone number.
        /// </summary>
        internal static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username or Password. Please Try Again..
        /// </summary>
        internal static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Time Zone: .
        /// </summary>
        internal static string LocalTime {
            get {
                return ResourceManager.GetString("LocalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region: .
        /// </summary>
        internal static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Types.
        /// </summary>
        internal static string ReportApptsByMonth {
            get {
                return ResourceManager.GetString("ReportApptsByMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Types By Country.
        /// </summary>
        internal static string ReportApptsByType {
            get {
                return ResourceManager.GetString("ReportApptsByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Schedule.
        /// </summary>
        internal static string ReportScheduleByContact {
            get {
                return ResourceManager.GetString("ReportScheduleByContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No appointment selected. Please select an appointment to update..
        /// </summary>
        internal static string SelectAppointment {
            get {
                return ResourceManager.GetString("SelectAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No customer selected. Please select a customer.
        /// </summary>
        internal static string SelectCustomer {
            get {
                return ResourceManager.GetString("SelectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a report type from the drop-down menu.
        /// </summary>
        internal static string SelectReport {
            get {
                return ResourceManager.GetString("SelectReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment added successfully!.
        /// </summary>
        internal static string SuccessAppointmentAdded {
            get {
                return ResourceManager.GetString("SuccessAppointmentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment deleted successfully!.
        /// </summary>
        internal static string SuccessAppointmentDeleted {
            get {
                return ResourceManager.GetString("SuccessAppointmentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment updated successfully!.
        /// </summary>
        internal static string SuccessAppointmentUpdated {
            get {
                return ResourceManager.GetString("SuccessAppointmentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer added successfully!.
        /// </summary>
        internal static string SuccessCustomerAdded {
            get {
                return ResourceManager.GetString("SuccessCustomerAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer deleted successfully!.
        /// </summary>
        internal static string SuccessCustomerDeleted {
            get {
                return ResourceManager.GetString("SuccessCustomerDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer updated successfully!.
        /// </summary>
        internal static string SuccessCustomerUpdated {
            get {
                return ResourceManager.GetString("SuccessCustomerUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Confirmation.
        /// </summary>
        internal static string UpdateConfirmation {
            get {
                return ResourceManager.GetString("UpdateConfirmation", resourceCulture);
            }
        }
    }
}
